# 服务器前置任务(ubuntu使用)
- name: redis
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt-get -y install python
  ignore_errors: yes


# 核心任务

- name: redis
  hosts: all
  become: yes
  become_method: sudo
  roles:
    - {role: common, tags: "common"}  
    - {role: redis, tags: "redis"}
