---
- name: Install Apache
  yum: 
    name: [httpd,mod_ssl]
    state: latest


- name: Create Vhost directory
  file: 
      path: /etc/httpd/vhost
      state: directory
 
- name: Create Data directory
  file: 
      path: /data/
      state: directory


- name: Create WebSite directory
  file: 
      path: /data/wwwroot/www.example.com
      state: directory
      owner: apache
      group: apache

- name: Create cert directory
  file: 
      path: /data/cert
      state: directory

- name: Copy Apache Configuration 
  copy: src=httpd.conf dest=/etc/httpd/conf/
  notify: restart Apache

- name: Copy Apache Vhost Configuration
  template: src=vhost.conf dest=/etc/httpd/vhost/vhost.conf
  notify: restart Apache


- block:
  - name: Install Certbot
    yum:
      name: [certbot,certbot-apache]
  rescue:
   - name: fix error
     pip:
       name: [requests==2.6.0,urllib3]
       extra_args: --upgrade --force-reinstall
  always:
    - name: Install Certbot
      yum:
        name: [certbot,certbot-apache]