- name: Import Nginx Official stable Repo
  yum_repository:
    name: nginx-stable-repo
    description: nginx stable repo
    file: nginx-stable
    baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://nginx.org/keys/nginx_signing.key

- name: Import Nginx Official mainline Repo
  yum_repository:
    name: nginx-mainline-repo
    description: nginx mainline repo
    file: nginx-mainline
    baseurl: http://nginx.org/packages/mainline/centos/$releasever/$basearch/
    gpgcheck: yes
    enabled: no
    gpgkey: https://nginx.org/keys/nginx_signing.key


- name: Install Nginx
  yum:
    name: [nginx]

- name: Install Certbot
  yum:
    name: [certbot,certbot-nginx]
  ignore_errors: yes

- pip:
    name: [requests==2.6.0,urllib3]
    extra_args: --upgrade --force-reinstall