---
- name: create vm
  hosts: localhost
  connection: local
  gather_facts: False

- tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: 付费资源组
      name: MongoDB4.0-Ubuntu18.04
      vm_size: Standard_B1ms
      admin_username: websoft9
      ssh_password_enabled: yes
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: <your-ssh-public-key-data>
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
