---
# Zabbix
- name: Zabbix
  hosts: all
  become: yes
  become_user: root
  become_method: sudo 

  roles:
    - { role: ubuntu_common, tags: "ubuntu", when: "ansible_os_family == 'Debian'" }
    - { role: centos_common, tags: "centos", when: "ansible_os_family == 'RedHat'" }
    - { role: ubuntu_zabbix, tags: "ubuntu_zabbix", when: "ansible_os_family == 'Debian'" }
    - { role: centos_zabbix, tags: "centos_zabbix", when: "ansible_os_family == 'RedHat'" }
