---
- name: graylog2
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - { role: common , tags: "common"} 
    - { role: graylog2, tags: "graylog2" }
    - { role: nginx, tags: "nginx" }
