---
# EmpireCMS
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes

- name: Get MySQL Password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mysql_password
  
- name: create folder
  file:
    path: /data/wwwroot/empirecms
    state: directory
    mode: 0750

- name: Download EmpireCMS
  unarchive:
    src: "{{ EmpireCMS }}"
    dest: /data/wwwroot/empirecms
    owner: apache
    group: apache
    remote_src: yes

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Create EmpireCMS databases
  mysql_db:
    login_user: root
    login_password: "{{mysql_password.stdout}}"
    name: empirecms
    state: present


- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Change PHP Config file
  template: src=php.ini dest=/etc/php.ini

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["EmpireCMS"];'

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 770 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 660 {} \;

- name: System Upgrade
  yum: name=* state=latest

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750