- name: System update
  apt:
    name: '*'
    force_apt_get: True
    state: latest

- name: Install mysql
  apt:
    name: [mysql-server-5.7, libmysqlclient-dev]
    state: latest

# - name: copy mysqld.cnf
#   template:
#     src: mysqld.cnf
#     dest: /etc/mysql/mysql.conf.d/
#     owner: root
#     group: root
#     mode: 0644

- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: change root's password
  shell: mysql -uroot -e "update mysql.user set authentication_string=PASSWORD('123456'), plugin='mysql_native_password' where user='root';"

- name: flush privileges
  shell: mysql -uroot -e "flush privileges;"



