- name: Add Nginx repository
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: update
  yum: 
    name: '*'
    state: latest

- name: Install Nginx
  yum: name=nginx state=latest

- name: replace nginx.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/
    owner: root
    group: root
    mode: 0644

- name: delete default.conf
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: add gogs.conf
  template:
    src: gogs.conf
    dest: /etc/nginx/conf.d
    owner: root
    group: root
    mode: 0644

- name: start nginx
  service: name=nginx state=started enabled=yes