---
- name: Install Caddy
  yum: name=caddy state=latest

- name: Create WebSite directory
  file: 
      path: /data/wwwroot/www.example.com
      state: directory
      owner: caddy
      group: caddy

- name: Create cert directory
  file: 
      path: /data/cert
      state: directory

- name: Copy Caddy Configuration 
  copy: src=caddy.conf dest=/etc/caddy
  notify: restart caddy


- block:
  - name: Install Certbot
    yum:
      name: [certbot,certbot-nginx]
  rescue:
   - name: fix error
     pip:
       name: [requests==2.6.0,urllib3]
       extra_args: --upgrade --force-reinstall
  always:
    - name: Install Certbot
      yum:
        name: [certbot,certbot-nginx]