- import_tasks: CentOS.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Start Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes