- name: Install redis
  apt: 
    name: redis
  when: ansible_distribution == 'Ubuntu'

- name: Install redis
  yum: 
    name: redis
  when: ansible_distribution == 'CentOS'

  
- name: Start redis
  service:
    name: redis
    enabled: yes
    state: restarted


- name: Check redis Version
  shell: redis-server -v
  register: redis_ver
  notify: redis Version
