---
- name: Docker
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'

  roles:
    - { role: portainer, tags: "portainer" }
    - { role: end, tags: "end" }