- name: Install openjdk-8-jre-headless
  apt:
    name: openjdk-8-jre-headless
    state: latest

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: add APT repository
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
    echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: latest
    update_cache: yes

- name: Config elasticsearch
  shell: |
    sysctl -w vm.max_map_count=262144
    echo "vm.max_map_count=262144" | tee /etc/sysctl.d/elasticsearch.conf
    systemctl restart elasticsearch

- name: Restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes