---
- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Obtain mysql root's password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mysql_root_password

## wordpress
- name: Download wordpress
  unarchive:
    src: "{{ twentynineteen }}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Copy Apache Vhost Configuration
  template: src=vhost.conf dest=/etc/httpd/vhost/vhost.conf

- name: Create wordpress databases
  mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password.stdout }}"
    name: wordpress
    state: present

## discuz
- name: Download Discuz!X3.4
  git:
    repo: "{{ Discuz }}"
    dest: /data/wwwroot/discuz

- name: copy discuz config
  copy: src=config_global_default.php dest=/data/wwwroot/discuz/upload/config

# common
- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["WordPress", "Discuz"];'

# ====================change file permission========================================== #
- name: change Apache owner
  shell: chown apache. -R /data/wwwroot

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -type f -exec chmod 640 {} \;

# ====================change file permission========================================== #