- name: LAMP
  hosts: all
  become: yes
  become_method: sudo

  roles:
    - { role: common , tags: "common"} 
    - { role: apache , tags: "apache"}
    - { role: php , tags: "php"}
    - { role: mysql , tags: "mysql"}
    - { role: phpmyadmin , tags: "phpmyadmin"}
    - { role: 9panel , tags: "9panel"}
    - { role: other , tags: "other"}
    
