---
- name: system upgrade
  yum: 
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install dependence
  yum:
    name: [openssh-server, postfix, curl, openssl, tzdata] 
    state: present
  when: ansible_distribution == "CentOS"

- name: add gitlab-ce repo
  template:
    src: gitlab-ce.repo
    dest: /etc/yum.repos.d/gitlab-ce.repo
    owner: root
    group: root
    mode: 0640

- name: flush repository
  command: yum makecache
    warn: false

- name: Install GitLab
  yum:
    name: gitlab-ce
    state: latest

- name: Reconfigure GitLab (first run).
  command: 
    gitlab-ctl reconfigure
  notify: restart gitlab
