## 部署
- name: moodle
  hosts: moodle
  become: yes
  become_method: sudo

  roles:
    - {role: common, tags: "common"}
    - {role: apache, tags: "apache"}
    - {role: mysql, tags: "mysql"}
    - {role: php-fpm, tags: "php-fpm"}
    - {role: lamp, tags: "lamp"}
    - {role: phpmyadmin, tags: "phpmyadmin"}
    - {role: 9panel, tags: "9panel"}
    - {role: moodle, tags: "moodle"}