- name: Install dependence, memcached
  apt:
    name: [build-essential, python-dev, libffi-dev, libssl-dev, patch, memcached]
    state: latest

- name: pip upgrade 
  shell: pip install --upgrade pip

- name: install setuptools
  shell: pip install -U setuptools

- name: Install python-memcached, ReviewBoard
  pip:
    name: [python-memcached, ReviewBoard]
    state: present

- name: Installing Database Bindings -1
  apt:
    name: python-mysqldb
    state: latest

- name: Installing Database Bindings -2
  shell: pip install -U mysql-python

- name: Install other necesassary soft
  apt:
    name: [cvs, git-core, subversion, python-svn]

- name: Install mercurial
  shell: pip install -U mercurial

- name: helix-p4d
  shell: wget -qO - https://package.perforce.com/perforce.pubkey | sudo apt-key add -

- name: copy helix-p4d repo
  template:
    src: perforce.list
    dest: /etc/apt/sources.list.d/
    owner: root
    group: root
    mode: 0644

- name: update 
  shell: apt update

- name: Install helix-p4d
  apt:
    name: helix-p4d
    state: latest

- name: Install p4python
  pip:
    name: p4python
    state: latest

- name: Install python-subvertpy & python-svn
  apt: 
    name: [subversion, python-svn]
    state: latest

- name: Create database
  mysql_db:
    name: reviewboard
    state: present
    login_user: root
    login_password: 123456