---
- name: Superset
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
  - { role: common , tags: "common"} 
  - { role: mysql , tags: "mysql"}
  - { role: superset  , tags: "superset"} 
  - { role: nginx , tags: "nginx"}



  


    


