- name: gogs
  hosts: all
  remote_user: root

  roles:
    - { role: common, tags: "common" }
    - { role: gogs, tags: "gogs" }
    - { role: mysql, tags: "mysql" }
    - { role: nginx, tags: "nginx" }
    