- name: gogs
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  roles:
    - { role: common, tags: "common" }
    - { role: gogs, tags: "gogs" }
    - { role: mysql, tags: "mysql" }
    - { role: nginx, tags: "nginx" }
    