---
# Dolibarr
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes
  
- name: Get MySQL Password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mysql_password

- name: Download Matomo
  unarchive:
    src: "{{ Matomo }}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Create Matomo databases
  mysql_db:
    login_user: root
    login_password: "{{mysql_password.stdout}}"
    name: Matomo
    state: present

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Matomo"];'

- name: Permission directory & file
  shell: | 
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest

- name: Databases Random Password
  copy: 
    src: init-57.sh
    dest: /root/init.sh
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750