---
- name: trac
  hosts: all
  remote_user: root

  roles:
    - { role: common, tags: common }
    - { role: nginx, tags: nginx }
    # - { role: apache2, tags: apache2}
    - { role: mysql, tags: mysql }
    - { role: trac, tags: trac }