---
- import_playbook: instance/aws.yml

- name: trac
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: yes


  roles:
    - { role: common, tags: common }
    - { role: nginx, tags: nginx }
    - { role: mysql, tags: mysql }
    - { role: trac, tags: trac }