---

- name: Add Nginx repository
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/
    owner: root
    group: root
    mode: 0644

- name: update
  yum: 
    name: '*'
    state: latest

- name: Install Nginx
  yum: name=nginx state=latest

- name: Create WebSite directory
  file: 
      path: /data/wwwroot/www.example.com
      state: directory
      owner: nginx
      group: nginx

- name: Create cert directory
  file: 
      path: /data/cert
      state: directory

- name: Copy Nginx Configuration 
  copy: src=nginx.conf dest=/etc/nginx
  notify: restart nginx

- name: Copy Nginx PHP support Configuration 
  copy: src=php.conf dest=/etc/nginx
  notify: restart nginx

- name: Copy Nginx other Configuration I
  copy: src=conf.d dest=/etc/nginx
  notify: restart nginx

- block:
  - name: Install Certbot
    yum:
      name: [certbot,certbot-nginx]
  rescue:
   - name: fix error
     pip:
       name: [requests==2.6.0,urllib3]
       extra_args: --upgrade --force-reinstall
  always:
    - name: Install Certbot
      yum:
        name: [certbot,certbot-nginx]