---
# NextCloud

- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes


# System upgrade

- name: System upgrade
  yum:
    name: '*'
    state: latest

## Install NextCloud
- name: Download NextCloud
  unarchive:
    src: "{{ NextCloud }}"
    dest: /data/wwwroot
    owner: apache
    group: apache
    remote_src: yes

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache

- name: Change 9panel
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"NextCloud","switch":0,'
    line: '{"appname":"NextCloud","switch":1,'

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: Permission occ
  file:
    path: /data/wwwroot/nextcloud/occ
    state: file
    mode: "u+x,g+x"

- name: copy config
  copy:
    src: config.php
    dest: /data/wwwroot/nextcloud/config
  notify: restart redis

- name: Set NextCloud Job
  command: php -f /data/wwwroot/nextcloud/cron.php

- name: NextCloud cron
  cron:
    name: "NextCloud cron"
    minute: "*/15"
    hour: "*"
    day: "*"
    month: "*"
    weekday: "*"
    user: apache
    job: "php -f /data/wwwroot/nextcloud/cron.php"

-  name: Set OPcache for NextCloud
   copy: src=10-opcache.ini dest=/etc/php.d/
   notify: restart Apache


