- name: upgrade pip
  shell: pip install --upgrade pip

- name: install subversion python-dev libmysqlclient-dev python-pexpect
  apt: 
    name: [subversion, python-dev, libmysqlclient-dev, python-pexpect, python-passlib]
    state: latest
    update-cache: yes

- name: install other Python Packages 
  pip:
    name: [genshi, Babel, docutils, Pygments, pytz, gunicorn]
    state: latest

- name: install trac
  pip:
    name: [trac, mysql-python]
    state: latest

- name: touch shell script
  copy:
    src: trac.exp
    dest: /root/trac.exp
    owner: root
    group: root
    mode: 0755

- name: Create Project Environment
  shell: expect ~/trac.exp

- name: delete ~/trac.exp
  file:
    path: ~/trac.exp
    state: absent

- name: create tracwsgi.py
  template:
    src: tracwsgi.py
    dest: /data/wwwroot/trac/tracwsgi.py
    mode: 0640

- name: generate user and password
  htpasswd:
    path: /etc/nginx/conf.d/users
    name: admin
    password: admin
    owner: root
    group: root
    mode: 0640


- name: create trac.service
  template:
    src: trac.service
    dest: /lib/systemd/system/trac.service
    mode: 0644
  notify: start trac

- name: copy trac's nginx configuration file
  template:
      src: default
      dest: /etc/nginx/sites-available/default
      mode: 0644
  notify: restart nginx

- name: Grant authorization to admin
  shell: trac-admin /data/wwwroot/trac permission add admin TRAC_ADMIN

- name: Setting rc.local
  file:
    path: /etc/rc.local
    state: touch
    mode: 0750

- name: Write rc.local
  shell: echo "#!/bin/bash" > /etc/rc.local

- name: restart rc.local
  service: name=rc.local state=restarted enabled=yes

- name: Write Databases Password
  shell: echo 'Databases root Password:'{{mysql_password}}  > /root/password.txt

- name: Password Text File Permission
  file:
    path: ~/password.txt
    mode: 0640
    
# - name: install usermanager plugin
#   shell: easy_install https://trac-hacks.org/svn/accountmanagerplugin/tags/acct_mgr-0.5.0
- name: Install usermanager plugin
  pip:
    name: TracAccountManager
    state: latest

- name: replace trac.ini
  copy:
    src: trac.ini
    dest: /data/wwwroot/trac/conf/
    mode: 0640
  notify: restart nginx

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750

- name: Setting File Permission
  shell: find /data/* -type f -exec chmod 640 {} \;

- name: Setting Directory Permission
  shell: find /data/* -type d -exec chmod 750 {} \; 