- name: upgrade pip
  shell: pip install --upgrade pip

- name: install subversion
  apt: name=subversion state=latest

- name: install python-dev
  apt: name=python-dev state=latest

- name: install other Python Packages 
  pip:
    name: [genshi, Babel, docutils, Pygments, pytz, gunicorn]
    state: latest

- name: install trac
  pip:
    name: [trac, mysql-python]
    state: latest

- name: touch shell script
  copy:
    src: trac.exp
    dest: /root/trac.exp
    owner: root
    group: root
    mode: 0755

- name: install expect
  apt:
    name: expect
    state: latest

- name: Create Project Environment
  shell: expect ~/trac.exp

# - name: deploy
#   shell: trac-admin /data/wwwroot/trac/trac deploy /data/wwwroot/trac/

- name: delete ~/trac.exp
  file:
    path: /root/trac.exp
    state: absent

- name: create tracwsgi.py
  template:
    src: tracwsgi.py
    dest: /data/wwwroot/trac/tracwsgi.py

- name: gnuicorn
  shell: cd /data/wwwroot/trac/ && gunicorn -D -w2 tracwsgi:application -b localhost:8000

- name: copy trac configuration file
  template:
      src: trac
      dest: /etc/nginx/sites-available/trac
      mode: 0644

- name: create soft link for trac
  file: 
    src: /etc/nginx/sites-available/trac
    dest: /etc/nginx/sites-enabled/trac
    state: link
    
- name: restart nginx
  service:
      name: nginx
      state: restarted

