- name: upgrade pip
  shell: pip install --upgrade pip

- name: install subversion python-dev libmysqlclient-dev python-pexpect
  apt: 
    name: [subversion, python-dev, libmysqlclient-dev, python-pexpect, python-passlib]
    state: latest
    update-cache: yes

- name: install other Python Packages 
  pip:
    name: [genshi, Babel, docutils, Pygments, pytz, gunicorn]
    state: latest

- name: install trac
  pip:
    name: [trac, mysql-python]
    state: latest

- name: touch shell script
  copy:
    src: trac.exp
    dest: /root/trac.exp
    owner: root
    group: root
    mode: 0755

- name: Create Project Environment
  shell: expect ~/trac.exp

- name: delete ~/trac.exp
  file:
    path: /root/trac.exp
    state: absent

# - name: Create Project Environment of trac
#   expect:
#     command: trac-admin /data/wwwroot/trac initenv
#     responses:
#       '[My Project]': 'trac'
#       '[sqlite:db/trac.db]': 'mysql://root:123456@localhost:3306/trac'
#     timeout: 60
#     echo: yes

- name: create tracwsgi.py
  template:
    src: tracwsgi.py
    dest: /data/wwwroot/trac/tracwsgi.py
    mode: 0640

- name: generate user and password
  htpasswd:
    path: /etc/nginx/conf.d/users
    name: admin
    password: admin
    owner: root
    group: root
    mode: 0640

- name: Create Trac PID Dir
  file:
    path: /run/trac
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create trac.service
  template:
    src: trac.service
    dest: /lib/systemd/system/trac.service
    mode: 0644
  notify: start trac

- name: copy trac's nginx configuration file
  template:
      src: default
      dest: /etc/nginx/sites-available/default
      mode: 0644
  notify: restart nginx

