---
- name: System Upgrade
  yum: name=* state=latest

- name: Install EPEL
  yum: name=epel-release state=installed


- name: Install REMI Repo
  yum: name=https://mirrors.tuna.tsinghua.edu.cn/remi/enterprise/remi-release-7.rpm

# - name: add dns for baiducloud
#   shell: echo "nameserver 8.8.8.8" >>/etc/resolv.conf

# - name: restart networdk
#   service: name=network state=restarted

- name: Install Common Software
  yum: 
    name: [yum-utils,wget,openssl,unzip,bzip2,expect,at,vim, screen, git, htop, yum-cron,ImageMagick, goaccess,MySQL-python,python-pip,redis]
    state: installed
  

- name: Configuration yum-cron
  copy: src=yum-cron.conf dest=/etc/yum/

- name: Start yum-cron
  service: name=yum-cron state=started enabled=yes

- name: Create swap Space
  command: dd if=/dev/zero of=/mnt/swap bs=256M count=8
  when: ansible_swaptotal_mb == 0

- name: Make swap
  command: mkswap /mnt/swap
  when: ansible_swaptotal_mb == 0

- name: Action swap
  command: swapon /mnt/swap
  when: ansible_swaptotal_mb == 0
  
- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "10"

- name: Add to fstab
  lineinfile:
      dest: /etc/fstab
      regexp: '/mnt/swap'
      line: "/mnt/swap swap swap defaults 0 0"
      state: present

- name: change swapfile permission
  file:
    path: /mnt/swap
    mode: 0600

- name: Start redis
  service: name=redis state=started enabled=yes