---
# VtigerCRM
# - import_tasks: install.yml
#   when: 
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes

  
- name: Download SuiteCRM
  unarchive:
    src: "{{ SuiteCRM }}"
    dest: /data/wwwroot
    owner: apache
    group: apache
    remote_src: yes

- name: Rename SuiteCRM Directory
  shell: mv /data/wwwroot/SuiteCRM-* /data/wwwroot/suitecrm

- name: fix Directory Permissions
  file:
    path: /data/wwwroot/suitecrm
    state: directory
    owner: apache
    recurse: yes

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent


- name: Copy PHP.ini
  copy:
    src: php.ini
    dest: /etc/

- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["SuiteCRM"];'

- name: System Upgrade
  yum: name=* state=latest


- name: Add cron job for SuiteCRM
  cron:
    name: SuiteCRM
    user: apache
    job: "cd /data/wwwroot/suitecrm; php -f cron.php > /dev/null 2>&1"


- name: Add cron job for SuiteCRM
  cron:
    name: SuiteCRM1
    user: apache
    job: "sudo crontab -e -u apache"

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750

- name: start redis
  service: name=redis state=started enabled=yes

- name: Permission directory
  shell: find /data/* -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/* -not -type d -exec chmod 640 {} \;