- name: Get MySQL Password
  shell: cat /credentials/password.txt |awk 'NR==2'|awk -F ":" '{print $2}'
  register: mysql_pass

- block:
  - name: Change MySQL Server Bind Address
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp: 'bind-address'
      state: absent

  - name: Restarted MySQL 
    service:
      name: mysql
      state: restarted
      enabled: yes

  when: ansible_distribution == 'Ubuntu'

- name: Create Remote User
  mysql_user: 
    login_user: root 
    login_password: "{{mysql_pass.stdout}}"
    name: root
    host: '%'
    password: "{{mysql_pass.stdout}}"
    priv: '*.*:ALL'

- name: Drop localhost User
  mysql_user:
    login_user: root 
    login_password: "{{mysql_pass.stdout}}"
    name: root
    host: '{{item}}'
    state: absent
  with_items:
    - localhost
    - 127.0.0.1
    - ::1


  ### 创建phpMyAdmin容器
- name: Started Docker Service
  service:
    name: docker
    state: started
    enabled: yes

- name: pull an phpMyAdmin
  shell: docker pull phpmyadmin/phpmyadmin
      

- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: gateway

- name: Create a phpMyAdmin container
  shell: docker run --name phpmyadmin -d -e PMA_HOST={{gateway.stdout}} -p 9090:80 --restart=always phpmyadmin/phpmyadmin
