---
- name: OnlyOfiice Documen Server
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  
  roles:
    - { role: documentserver , tags: "documentserver"} 
    - { role: nginx , tags: "nginx"} 