# PostgrepSQL 开启远程
- name: enable PostgrepSQL Remote connection I
  copy:
    src: pg_hba.conf
    dest: /data/pgsql

- name: enable PostgrepSQL Remote connection II
  copy:
    src: postgresql.conf
    dest: /data/pgsql
  
- name: Restarted PostgrepSQL
  shell: systemctl restart postgresql-*

#### 创建PostgrepSQL容器

- name: pull an PostgrepSQL
  shell: docker pull dockage/phppgadmin


- name: Get Docker Gateway
  shell: ip route show | grep docker0 | awk '{print $9}'
  register: gateway

- name: Create a PostgrepSQL container
  shell: docker run --name phpmyadmin -d -e PHP_PG_ADMIN_SERVER_HOST={{gateway.stdout}} -p 9090:80 --restart=always dockage/phppgadmin
