---
# 禅道
- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes

- name: Remove already existing zentao
  file:
    path: /data/wwwroot/zentao
    state: absent
  
- name: Download ZenTaoPMS
  unarchive:
    src: "{{ ZenTaoPMS }}"
    dest: /data/wwwroot
    remote_src: yes
    owner: apache
    group: apache

- name: Rename
  shell: mv /data/wwwroot/zen* /data/wwwroot/zentao

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent
    
- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost

- name: restart Apache
  service: name=httpd state=restarted enabled=yes

- name: Enable 9panel I
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps=["Zentao"];'

- name: Permission directory
  shell: find /data/wwwroot -type d -exec chmod 750 {} \;
  
- name: Permission file
  shell: find /data/wwwroot -not -type d -exec chmod 640 {} \;

- name: System Upgrade
  yum: name=* state=latest

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750
