---
- name: onlyoffice
  hosts: local
  connection: local
  gather_facts: False
  pre_tasks:
    - name: Set Git repo
      shell: |
        git init
        git config core.sparsecheckout true
        git remote add origin https://github.com/Websoft9/ansible-roles.git
        echo {{ item }} >> .git/info/sparse-checkout
      args:
        chdir: roles
      with_items:
        - "{{ public_roles }}"

    - name: Get Public Roles
      git:
        repo: https://github.com/Websoft9/ansible-roles.git
        dest: roles
        clone: no

    - name: Delete .git
      file:
        path: roles/.git
        state: absent

- name: Odoo
  hosts: Odoo
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'

- hosts: Odoo
  become: yes
  become_method: sudo
  tasks:
    - {role: common, tags: "common"}
    - {role: nginx, tags: "nginx"}
    - {role: odoo, tags: "odoo"}



      
