---
# EspoCRM

- name: Get WebServer
  shell: nginx -v
  register: nginx_ver
  ignore_errors: yes


- name: Download EspoCRM
  unarchive:
    src: "{{ EspoCRM }}"
    dest: /data/wwwroot
    owner: apache
    group: apache
    remote_src: yes

- name: Rename folder
  shell: mv /data/wwwroot/EspoCRM-* /data/wwwroot/espocrm

- name: Remove example dir
  file:
    path: /data/wwwroot/www.example.com
    state: absent

- name: Create EspoCRM databases
  mysql_db:
    login_user: root
    login_password: 123456
    name: espocrm
    state: present


- name: Copy Apache Config
  template: src=vhost.conf dest=/etc/httpd/vhost
  notify: restart Apache

- name: Change PHP Config file
  template: src=php.ini dest=/etc/php.ini
  notify: restart Apache

- name: Change 9panel for EspoCRM
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: '{"appname":"EspoCRM","switch":0,'
    line: '{"appname":"EspoCRM","switch":1,'

- name: Permission directory
  shell: |
    find /data/wwwroot -type d -exec chmod 750 {} \;
    find /data/wwwroot -not -type d -exec chmod 640 {} \;
    echo "* * * * * cd /data/wwwroot/espocrm; /usr/bin/php -f cron.php > /dev/null 2>&1" >> /etc/crontab

# - name: create crontab task
#   shell: echo "* * * * * cd /data/wwwroot/espocrm; /usr/bin/php -f cron.php > /dev/null 2>&1" >> /etc/crontab
  
- name: System Upgrade
  yum: name=* state=latest

- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750