- name: Get mongodb root Default Password
  shell: cat /credentials/password.txt | awk 'NR==2' |awk -F ":" '{print $2}'
  register: mongodb_password 

- name: Stop mongodb
  service:
    name: mongod
    state: stopped

- name: config mongodb
  shell: |
    sudo sed -i "s/^#  engine:/  engine: mmapv1/"  /etc/mongod.conf
    sudo sed -i "s/  authorization: enabled/  authorization: disabled/" /etc/mongod.conf

- name: Delete mongodb databases
  shell: rm -rf /data/mongo/*

- name: Start mongodb
  service:
    name: mongod
    state: started

- wait_for: port=27017 delay=10

- name: Setting MongoDB Administrator User
  mongodb_user:
    database: admin
    name: root
    password: '{{ mongodb_password.stdout}}'
    roles: root
    state: present

- name: Create databases
  mongodb_user:
    login_user: root
    login_password: '{{mongodb_password.stdout}}'
    database: rocketchat
    name: rocketchat
    state: present
    password: websoft9
    roles: readWrite

- name: config mongodb
  shell: |
    sudo sed -i "s/^#replication:/replication:\n  replSetName: rs01/" /etc/mongod.conf

- name: Enable MongoDB authorization
  lineinfile:
    path: /etc/mongod.conf
    regexp: '  authorization: disabled'
    line: '  authorization: enabled'

- name: restart MongoDB
  service: name=mongod state=restarted enabled=yes

- name: printjson
  shell: mongo -u root -p {{ mongodb_password.stdout }} --eval "printjson(rs.initiate())"

- name: Create  User
  user:
    name: rocketchat
    shell: /usr/sbin/nologin
    home: /data/wwwroot/Rocket.Chat
    create_home: no

- name: Create Directory 
  file:
    path: /data/wwwroot/
    state: directory
    owner: rocketchat
    group: rocketchat

- name: Install graphicsmagick
  apt:
    name: graphicsmagick
    update_cache: yes

- name: Download Rocket.Chat
  unarchive:
    src: https://releases.rocket.chat/latest/download
    dest: /tmp
    remote_src: yes

- name: Install Rocket.Chat
  shell: sudo mv /tmp/bundle /data/wwwroot/Rocket.Chat

- name: Installation dependency
  shell: sudo npm install
  args:
    chdir: /data/wwwroot/Rocket.Chat/programs/server

- name: Configuration Rocket.Chat
  template:
    src: rocketchat.conf.jinja2
    dest: /data/wwwroot/Rocket.Chat/rocketchat.conf

- name: Configuration Rocket.Chat systemctl
  copy:
    src: rocketchat.service
    dest: /lib/systemd/system/

- name: Start Rocket.Chat
  service:
    name: rocketchat.service
    state: restarted
    enabled: yes

- name: set reverse porxy
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: Write Databases Password
  template:
    src: password.txt.jinja2
    dest: /credentials/password.txt
    mode: 644

- name: Write rc.local
  shell: echo "#!/bin/bash" > /etc/rc.local

- name: restart rc.local
  service: name=rc.local state=restarted enabled=yes


- name: Databases Random Password
  template: 
    src: init.sh.jinja2
    dest: /root/init.sh
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750