- name: Reload apache
  service:
    name: apache2
    state: reloaded
    enabled: yes

- name: Restart elasticsearch
  service: 
    name: elasticsearch
    state: restarted
    enabled: yes

- name: Restart MySQL
  service:
    name: mysql
    state: restarted
    enabled: yes

