- import_tasks: CentOS.yml
  when: ansible_distribution == 'CentOS'

- import_tasks: Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'


- name: Configure Nginx
  copy:
    src: nginx.conf
    dest: /etc/nginx/


- name: Start Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Check Nginx Version
  shell: nginx -v
  register: nginx_ver
  notify: Nginx Version