## IIS
- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: no
    include_management_tools: yes
  register: win_feature

- name: Create IIS lnk
  win_shortcut:
    src: C:\windows\system32\inetsrv\InetMgr.exe
    dest: C:\Users\Public\Desktop\Internet Information Services (IIS) Manager.lnk
    directory: C:\windows\system32\inetsrv\

- name: Reboot if installing Web-Server feature requires it
  win_reboot:
  when: win_feature.reboot_required