---
- name: redmine
  hosts: all
  remote_user: '{{admin_username}}'

  roles:
    - { role: common , tags: "common"} 
    - { role: nginx , tags: "nginx"}
    - { role: mysql , tags: "mysql"}
    - { role: redmine, tags: "redmine"}