- name: install Postfix to send notification emails
  apt:
    name: postfix

- name: Add the GitLab package repository and install the package
  shell: curl -sS https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh | sudo bash


- name: Install GitLab package
  apt:
    name: gitlab-ce


- name: Reconfigure GitLab (first run).
  shell: gitlab-ctl reconfigure
