---
- name: System Upgrade
  apt:
    name: '*'
    state: latest
    force_apt_get: True

- name: Prerequisites
  apt:
    name: [apt-transport-https, openjdk-8-jre-headless, uuid-runtime, pwgen]
    state: latest

- name: MongDB
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: add reporisity 
  shell: echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list

- name: install MongDB
  apt: 
    name: mongodb-org
    state: latest
    update-cache: yes

- name: start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes

- name: Install Elasticsearch -1
  shell: |
    wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
    echo "deb https://artifacts.elastic.co/packages/oss-6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: Install Elasticsearch -2
  apt: 
    name: elasticsearch-oss 
    state: latest
    update-cache: yes

- name: change elasticsearch's configuration file
  template:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/
    owner: root
    group: root
    mode: 0644

- name: start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: yes

- name: graylog -1
  apt:
    deb: https://packages.graylog2.org/repo/packages/graylog-3.1-repository_latest.deb

- name: graylog -2
  apt:
    name: graylog-server
    state: latest
    update_cache: yes

- name: change configuration file
  template:
    src: server.conf
    dest: /etc/graylog/server/
    owner: root
    group: root
    mode: 0644

- name: start graylog2
  service:
    name: graylog-server
    state: started
    enabled: yes
