---
- include_vars: ../../mysql/defaults/main.yml

- name: add Oracle JAVA PPA
  apt_repository:
    repo: ppa:webupd8team/java 

- name: Accept oracle license
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: 'true'
    vtype: select

- name: Install Open JAVA
  apt:
    name: [openjdk-8-jdk]
    state: latest

- name: Download knowage
  unarchive:
    src: '{{knowage_url}}'
    dest: '{{ansible_user_dir}}'
    remote_src: yes
    mode: 0750
                                          
- name: Rename install package
  shell: mv Knowage-*.sh  Knowage-CE-Installer-Unix.sh
  args:
    chdir: '{{ansible_user_dir}}'

- name: create dir
  file:
    path: /data/wwwroot/
    state: directory

- name: setting MySQL
  copy:
    src: mysqld.cnf
    dest: /etc/mysql/mysql.conf.d
  notify: restart mysql

- name: upload Install script
  template:
    src: install.sh
    dest: '{{ansible_user_dir}}'
    mode: 0750

- name: install Knowage
  shell: '{{ansible_user_dir}}/install.sh '     

- name: Setting JRE Securerandom
  lineinfile:
    path: /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/java.security
    regexp: 'securerandom.source=file:/dev/random'
    line: 'securerandom.source=file:/dev/./urandom'

- name: Create User for Knowage
  user:
    name: knowage
    create_home: no
    home: /data/wwwroot/Knowage-Server-CE
    shell: /usr/sbin/nologin

- name: Change Directory owner
  file:
    path: /data/wwwroot/Knowage-Server-CE
    state: directory
    owner: knowage
    group: knowage
    recurse: yes

- name: Setting rc.local
  file:
    path: /etc/rc.local
    state: touch
    mode: 0750

- name: Write rc.local
  shell: echo "#!/bin/bash" > /etc/rc.local

- name: restart rc.local
  service: name=rc.local state=restarted enabled=yes

- name: Create credentials Folder
  file:
    path: /credentials
    state: directory

- name: Create Password doc
  file:
    path: /credentials/password.txt
    mode: 644
    state: touch

- name: Write Databases Password
  shell: echo -e 'MySQL username:root\nMySQL Password:'{{mysql_password}}  > /credentials/password.txt


- name: Databases Random Password
  copy: 
    src: init.sh
    dest: /root/
    mode: 0750

- name: Setting Startup
  lineinfile:
    path: /etc/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750


- name: Change Directory owner
  file:
    path: /data/wwwroot/Knowage-Server-CE
    state: directory
    owner: knowage
    group: knowage
    recurse: yes


- name: Setting Knowage Service
  copy:
    src: knowage.service
    dest: /lib/systemd/system
  notify: restart knowage


- name: Delete package
  file:
    path: "{{ansible_user_dir}}/{{item}}"
    state: absent
  with_items:
   - "{{ansible_user_dir}}/install.sh"
   - "{{ansible_user_dir}}/Knowage-CE-Installer-Unix.sh"

