---
- name: Set PHP version
  command: yum-config-manager --enable remi-php{{ phpver }}


- name: Install PHP{{ phpver }}
  yum: 
    name: [php-fpm,php-pecl-imagick,php-mysql,php-common,php-gd,php-mbstring,php-mcrypt,php-devel,php-xml,php-pdo,php-bcmath,php-pear,php-opcache,php-ldap,php-odbc,php-xmlrpc,php-json,php-mysqlnd,php-pdo,php-pdo_dblib ,php-recode,php-snmp,php-soap,php-pecl-zip,php-curl,php-imap,php-pear-Net-SMTP,php-pear-Mail]
    state: present
  when: phpver != 54

- name: Install PHP54
  yum: 
    name: [php-fpm,php-pecl-imagick,php-mysql,php-common,php-gd,php-mbstring,php-mcrypt,php-devel,php-xml,php-pdo,php-bcmath,php-pear,php-opcache,php-ldap,php-odbc,php-xmlrpc,php-json,php-pdo,php-pdo_dblib,php-recode,php-snmp,php-soap,php-pecl-zip,php-curl,php-imap,php-pear-Net-SMTP,php-pear-Mail]
    state: present
  when: phpver == 54


- name: Copy PHP Configuration 
  template: src=php.ini dest=/etc/
  notify: restart php

- name: Copy PHP-FPM Configuration 
  copy: src=www.conf dest=/etc/php-fpm.d/
  notify: restart php


- name: PHP-FPM update fixed
  lineinfile: 
    dest: /etc/cron.daily/0yum-daily.cron
    line: 'chown caddy. -R /var/lib/php'

- name: PHP Session/Cache fixed
  file:
    path: /var/lib/php
    owner: caddy
    group: caddy
    state: directory
    recurse: yes

