---
- name: ActiveMQ
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'

- name: ActiveMQ
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  
  tasks:
    - include_tasks: common.yml

    - name: Install JDK
      apt:
        name: openjdk-8-jdk

    - name: Add ActiveMQ User
      user:
       name: activemq
       shell: /usr/sbin/nologin
       home: /opt/apache-activemq
       create_home: no

    - name: Download ActiveMQ
      unarchive:
        src: http://mirror.bit.edu.cn/apache//activemq/5.15.9/apache-activemq-5.15.9-bin.tar.gz
        dest: /opt/
        remote_src: yes
        owner: activemq
        group: activemq
        
    - shell: mv /opt/apache-activemq-* /opt/apache-activemq

    - shell: chmod +x /opt/apache-activemq/bin/activemq

    - name: Setting Environment
      shell: echo 'export PATH="$PATH:/opt/apache-activemq/bin"' >> /etc/profile

    - name: Configuration ActiveMQ Server
      copy:
        src: activemq.service
        dest: /lib/systemd/system/
  
    - name: Start ActiveMQ
      service:
        name: activemq
        state: started
        enabled: yes


    - name: Setting File Permission
      shell: chmod 640  /opt/apache-activemq/examples/stomp/php/*

    - name: Setting Owner and  Group
      shell: chown -R activemq. /opt/apache-activemq


    - name: Remove SSH info
      file: 
        path: '{{item}}'
        state: absent
      with_items:
        - /home/{{admin_username}}/.ssh
        - /root/.ssh
