---
- name: KafkaMQ
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'

- name: KafkaMQ
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  
  tasks:
    - include_tasks: common.yml
    
    - name: Install JDK
      apt:
        name: openjdk-8-jdk

    - name: Add Kafka User
      user:
       name: kafka
       shell: /usr/sbin/nologin
       home: /opt/kafka
       create_home: no

    - name: Download Kafka
      unarchive:
        src: http://mirrors.hust.edu.cn/apache/kafka/2.1.0/kafka_2.12-2.1.0.tgz
        dest: /opt/
        remote_src: yes
        owner: kafka
        group: kafka
        
    - shell: mv /opt/kafka_* /opt/kafka

    - name: Setting Environment
      shell: echo 'export PATH="$PATH:/opt/kafka/bin"' >> /etc/profile

    - name: Configuration Zookeeper 
      copy:
        src: zookeeper.properties
        dest: /opt/kafka/config
        owner: kafka 
        group: kafka

    - name: Configuration Kafka
      lineinfile:
        path: /opt/kafka/config/server.properties
        regexp: 'log.dirs=/tmp/kafka-logs'
        line: 'log.dirs=/opt/kafka/kafka-logs'
        owner: kafka 
        group: kafka


    - name: Configuration Zookeeper Server
      copy:
        src: zookeeper.service
        dest: /lib/systemd/system/

    - name: Configuration Kafka Server
      copy:
        src: kafka.service
        dest: /lib/systemd/system/
  
    - name: Start Zookeeper
      service:
        name: zookeeper
        state: started
        enabled: yes

    - name: Start kafka
      service:
        name: kafka
        state: started
        enabled: yes

    # - name: Setting File Permission
    #   shell: find /opt -type f -exec chmod 640 {} \;

    # - name: Setting Directory Permission
    #   shell: find /opt -type d -exec chmod 750 {} \;  

    - name: Setting Owner and  Group
      shell: chown -R kafka. /opt/kafka

    - name: Remove SSH info
      file: 
        path: '{{item}}'
        state: absent
      with_items:
        - /home/{{admin_username}}/.ssh
        - /root/.ssh