---
- name: RocketMQ
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  gather_facts: False
  pre_tasks:
   - name: 'install python'
     raw: 'sudo apt-get -y install python'

- name: RocketMQ
  hosts: all
  become: yes
  become_method: sudo
  become_user: root
  remote_user: '{{admin_username}}'
  
  tasks:
    - include_tasks: common.yml
    
    - name: Install JDK
      apt:
        name: openjdk-8-jdk

    - name: Add RocketMQ User
      user:
       name: rocketmq
       shell: /usr/sbin/nologin
       home: /opt/rocketmq
       create_home: no

    - name: Download RocketMQ
      unarchive:
        src: http://mirrors.tuna.tsinghua.edu.cn/apache/rocketmq/4.4.0/rocketmq-all-4.4.0-bin-release.zip
        dest: /opt/
        remote_src: yes
        owner: rocketmq
        group: rocketmq
        
    - shell: mv /opt/rocketmq-* /opt/rocketmq

    - name: Setting Environment
      shell: echo 'export PATH="$PATH:/opt/rocketmq/bin"' >> /etc/profile

    - name: Configuration Name Server
      copy: 
        src: runserver.sh
        dest: /opt/rocketmq/bin/
        owner: rocketmq
        group: rocketmq

    - name: Configuration Broker
      copy: 
        src: runbroker.sh
        dest: /opt/rocketmq/bin/
        owner: rocketmq
        group: rocketmq
        
    - name: Configuration RocketMQ Name Server
      copy:
        src: mqnamesrv.service
        dest: /lib/systemd/system/

    - name: Configuration RocketMQ Broker Server
      copy:
        src: mqbroker.service
        dest: /lib/systemd/system/
  
    - name: Start RocketMQ Name Server
      service:
        name: mqnamesrv
        state: started
        enabled: yes

    - name: Start RocketMQ Broker Server
      service:
        name: mqbroker
        state: started
        enabled: yes

    # - name: Setting File Permission
    #   shell: find /opt -type f -exec chmod 640 {} \;

    # - name: Setting Directory Permission
    #   shell: find /opt -type d -exec chmod 750 {} \;  

    - name: Setting Owner and  Group
      shell: chown -R rocketmq. /opt/rocketmq


    - name: Remove SSH info
      file: 
        path: '{{item}}'
        state: absent
      with_items:
        - /home/{{admin_username}}/.ssh
        - /root/.ssh