- name: APT update
  command: apt update

- name: Upgrade System
  apt:
    name: "*"
    state: latest
    force_apt_get: True
  
- name: Install System Required
  apt:
    name: [postgresql,ttf-wqy-zenhei,ttf-wqy-microhei,htop,git]
    update_cache: yes
    force_apt_get: True   
  
- name: add Odoo key
  apt_key:
    url: https://nightly.odoo.com/odoo.key
      
- name: add Odoo Repository
  apt_repository:
    repo: deb http://nightly.odoo.com/13.0/nightly/deb/ ./
    filename: odoo


- name: Install Odoo
  apt:
    name: odoo
    update_cache: yes
    force_apt_get: True 

- name: Install wkhtmltox
  apt:
    deb: https://downloads.wkhtmltopdf.org/0.12/0.12.5/wkhtmltox_0.12.5-1.{{ansible_lsb.codename}}_amd64.deb

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
    force_apt_get: True

- name: copy  wkhtmltox
  command: cp /usr/local/bin/wkhtmltopdf /usr/bin/

- name: Config Odoo
  copy:
    src: odoo.conf
    dest: /etc/odoo/

- name: Config Nginx
  copy:
    src: default
    dest: /etc/nginx/conf.d/default.conf


- name: Started Odoo
  service:
    name: odoo
    state: restarted
    enabled: yes

- name: Started Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: Started PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes
