---
- name: Install docker
  yum: 
    name: docker
    state: latest

- name: start docker
  service: 
    name: docker 
    state: started 
    enabled: yes

- name: Install docker-py module
  pip:
    name: docker-py

- name: Create /data directory
  file:
    path: /data
    state: directory
    owner: root
    group: root
    mode: 0755

- name: pull portainer image
  docker_image:
    name: portainer/portainer

- name: Create a volume
  docker_volume:
    name: portainer_data

# - name: start portainer
#   docker_container:
#     name: portainer
#     image: portainer/portainer
#     volumes: 
#       - "/var/run/docker.sock:/var/run/docker.sock"
#       - "portainer_data:/data"
    
    
- name: start portainer
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    restart_policy: always
    ports:
      - "9000:9000"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    