---
- name: Install Nginx
  yum: name=nginx state=latest

- name: Delete Nginx User
  user:
    name: nginx
    state: absent 
    remove: yes 

- name: Create www User
  user:
    name: www
    shell: /sbin/nologin
    append: yes
    createhome: no
    home: /data/wwwroot/

- name: Create Date directory
  file: 
    path: /data/
    state: directory


- name: Create WebSite directory
  file: 
      path: /data/wwwroot/www.example.com
      state: directory
      owner: www
      group: www


- name: Create cert directory
  file: 
      path: /data/cert
      state: directory


- name: fixed some problem
  file:
    path: /var/lib/nginx/tmp/client_body
    state: directory
    owner: www
    group: www

- name: Copy Nginx Configuration 
  copy: src=nginx.conf dest=/etc/nginx
  notify: restart Nginx

- name: Copy Nginx JSP support Configuration 
  copy: src=jsp.conf dest=/etc/nginx
  notify: restart Nginx

- name: Copy Nginx other Configuration I
  copy: src=conf.d dest=/etc/nginx
  notify: restart Nginx

- block:
  - name: Install Certbot
    yum:
      name: [certbot,certbot-nginx]
  rescue:
   - name: fix error
     pip:
       name: [requests==2.6.0,urllib3]
       extra_args: --upgrade --force-reinstall
  always:
    - name: Install Certbot
      yum:
        name: [certbot,certbot-nginx]