---
- name: Import Node.js repo
  shell: curl -sL https://rpm.nodesource.com/setup_{{nodejs_ver}}.x | bash -

- name: Import yarn repo
  shell: curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo

- name: Install Node.js and Yarn
  yum:
    name: [nodejs,gcc-c++,make,yarn]
    
- name: Install PM2
  npm:
    name: pm2
    global: yes

- name: Install express generator
  npm:
    name: express-generator
    global: yes

- name: Install Nginx
  yum:
    name: nginx
    
- name: Setting Nginx I
  copy:
    src: nginx.conf
    dest: /etc/nginx/

- name: Setting Nginx II
  copy:
    src: conf.d
    dest: /etc/nginx/

- name: Create dir
  file:
    path: /data/wwwroot/
    state: directory


- name: Create Demo Project
  shell: express project
  args:
    chdir: /data/wwwroot/
    
- name: Install Demo Project module
  npm:
    path: /data/wwwroot/project

- name: PM2 Start Demo Project
  shell: pm2 start bin/www
  args:
    chdir: /data/wwwroot/project

- name: Save PM2 configure
  shell: pm2 save
  args:
    chdir: /data/wwwroot/project

- name: Setting pm2 Startup
  shell: pm2 startup
  args:
    chdir: /data/wwwroot/project

- name: Start pm2 
  service:
    name: pm2-root
    state: restarted
    enabled: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

# - name: Setting File Permission
#   shell: find /data/* -type f -exec chmod 640 {} \;

# - name: Setting Directory Permission
#   shell: find /data/* -type d -exec chmod 750 {} \;   