---
# 创建临时解压目录
- name: create temporary directory to extract sqlserver
  win_file:
    path: C:\temp\{{sqlserver_name}}

# 解压
- name: unzip {{sqlserver_name}}
  win_shell:
    .\{{sqlserver_name}}.exe /u /x:c:\temp\{{sqlserver_name}}
  args:
    chdir: C:\temp\

# 安装
- name: Copy ConfigurationFile.ini
  win_template:
    src: ConfigurationFile.ini.j2
    dest: C:\temp\{{sqlserver_name}}\ConfigurationFile.ini

- name: Install {{sqlserver_name}}
  win_shell:
    .\SETUP.EXE /Q /IACCEPTSQLSERVERLICENSETERMS /ACTION=install /ConfigrationFile=ConfigrationFile.ini
  args:
    chdir: C:\temp\{{sqlserver_name}}
  become: yes

## 快捷方式
- name: Create SSMS lnk
  win_shortcut:
    src: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\Ssms.exe
    dest: C:\Users\Public\Desktop\SQL Server 2012 Management Studio.lnk
    icon: C:\Program Files (x86)\Microsoft SQL Server\110\Tools\Binn\ManagementStudio\ssms.ico