---
## 安装jdk1.8
- name: install openjdk1.8
  include: jdk.yml

## 解压
- name: unzip {{sqlserver_name}}
  win_shell:
    .\{{sqlserver_name}}.exe /u /x:c:\temp\{{sqlserver_name}}
  args:
    chdir: C:\temp\

# ## 安装
# - name: Copy ConfigurationFile.ini
#   win_template:
#     src: ConfigurationFile_CHS.ini.j2
#     dest: C:\temp\{{sqlserver_name}}\ConfigurationFile.ini

- name: Install SQLServer2016
  win_shell:
    .\SETUP.EXE /q /IACCEPTSQLSERVERLICENSETERMS /SUPPRESSPRIVACYSTATEMENTNOTICE /ACTION=Install /UpdateEnabled=0 /ENU=false /FEATURES=SQL /SECURITYMODE=SQL /SQLSYSADMINACCOUNTS="{{ansible_hostname}}\administrator" /INSTANCENAME=MSSQLSERVER  /SAPWD="Web#123456" /ISSVCSTARTUPTYPE=Automatic /BROWSERSVCSTARTUPTYPE=Automatic /SQLSVCSTARTUPTYPE=Automatic /TCPENABLED=1 /SQLSVCACCOUNT="NT Service\MSSQLSERVER"
  args:
    chdir: C:\temp\{{sqlserver_name}}
  become: yes

