## 安装SSMS
- name: Download SSMS
  win_get_url:
    url: "{{ssms_download}}"
    dest: C:\temp\ssms.exe

- name: Install SSMS
  win_shell:
    .\ssms.exe /install /quiet /norestart
  args:
    chdir: C:\temp

## 快捷方式
- name: Create SSMS lnk
  win_shortcut:
    src: C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Ssms.exe
    dest: C:\Users\Public\Desktop\Microsoft SQL Server Management Studio 18.lnk
    icon: C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\ssms.ico