- block:
  - name: Write rc.local
    shell: echo "#!/bin/bash" > /etc/rc.local

  - name: restart rc.local
    service: name=rc.local state=restarted enabled=yes
  when: ansible_distribution == 'Ubuntu'


- name: upload random Script
  template:
    src: init.sh.jinja2
    dest: /root/init.sh
    mode: 750


- name: Setting Startup
  lineinfile:
    path: /etc/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750
  when: ansible_distribution == 'Ubuntu'


- name: Setting Startup
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: '/root/init.sh'
    line: '/root/init.sh'
    mode: 0750
  when: ansible_distribution == 'CentOS'